### ISSUE TITLE
polybar on ratpoison

### ISSUE THREAD

**Issue by drmarwat** [benofbrown/dotfiles#1]
how do you use polybar on ratpoison? do you launch it through your startup file? I did not find your startup file in your dots

**Comment by benofbrown** [comment]
Yes, I launch it in my startup file. It's not in the repo at the moment because it was very different across my work and home computer, but I've figured out how to handle that better now so I'll update the repo soon, but in the meantime here's my home one:

```
#!/bin/bash

(
xset -b
xsetroot -solid rgb:00/2b/36
xmodmap ~/.Xmodmap
polybar ben &
pkill redshift && redshift &
) >/dev/null 2>&1
```

**Comment by drmarwat** [comment]
Thanks for sharing your startup file.On your ratpoisonrc file you load it with "exec /home/ben/bin/startup.sh" which is from root directory. What if I load it from my home directory? will that make any difference?

**Comment by drmarwat** [comment]
Could you also share your polybar launch.sh file as well please ? My entry for loading polybar from ratpoison is 
#Polybar
unmanage panel
unmanage polybar
exec_always ~/.config/polybar/launch.sh &
is that looking good? I have been unable to load polybar with ratpoison till now .
One last question is that your polybar config file seems to be used with bspwm and i3 . Shouldnt it be having some lines for working with ratpoison ?

**Comment by benofbrown** [comment]
So instead of `launch.sh` I have that `startup.sh`. If you do something similar in your `launch.sh` it should be fine.

I only use polybar with ratpoison, though the config is based on the example one so it has that bspwm and i3 stuff in. If you look at the modules I've enabled you can see I'm not using those other wm ones. The only relevant file not in the repo is that `startup.sh` which I pasted in above.

**Comment by drmarwat** [comment]
I am pasting my current ploybar config file adopted from yours with some modifications. I need some helps here
- I added jgmenu module but it does not appear as expected on the left side of bar . Can you check what is wrong with my entry for jgmenu
- I want to remove i3 and bspwm modules and add a [module/ratpoison] but can`t find and example entry to make this module. Can you help me in this?
- I dont have any powermenu on the right end of the bar . What is causing it?

pasted is the config file I am using 

;==========================================================
;

[colors]
background = #002b36
background-alt = #444
foreground = #839496
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/ben]
width = 100%
height = 26
;offset-x = 1%
;offset-y = 1%
;radius = 6.0
fixed-center = false
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = Fantasque Sans Mono:style=Bold:pixelsize=14
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = Liberation Mono:style=Regular
font-3 = Symbola:style=Regular:pixelsize=16
font-4 = Fantasque Sans Mono:style=Regular

;modules-left = jgmenu bspwm i3
;modules-center = mpd
modules-right = filesystem pulseaudio memory cpu wlan eth battery temperature date powermenu

tray-position = right
tray-padding = 2
;tray-background = #0063ff

;wm-restack = bspwm
;wm-restack = i3
wm-name = polybar

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize

[bar/ben-work]
inherit = bar/ben
modules-left = jgmenu
height = 23
modules-right = workfilesystem pulseaudio memory cpu workwlan worketh battery temperature date
font-0 = Fantasque Sans Mono:style=Bold:pixelsize=10
font-4 = Fantasque Sans Mono:style=Regular:pixelsize=10
padding-left = 1
padding-right = 1

module-margin-left = 1
module-margin-right = 0


[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750


[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
mount-1 = /home
mount-2 = /boot

label-mounted = %{F#b58900}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint%
label-unmounted-font = 5
label-unmounted-foreground = ${colors.foreground-alt}

[module/workfilesystem]
inherit = module/filesystem
mount-2 = /usr/local
mount-3 = /home/ben/data

[module/jgmenu]
type = custom/script
label = %output%
label-padding = 2
interval = 10
exec = echo ""
click-left = "jgmenu_run >/dev/null 2>&1 &"
click-right = exo-open $HOME/.config/jgmenu/jgmenurc

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

; Separator in between workspaces
; label-separator = |

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

; Separator in between workspaces
; label-separator = |

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 2
format = <ramp-load>
format-prefix = "CPU "
format-prefix-foreground = ${colors.foreground-alt}
;format-underline = #f90000
label = %percentage:2%%
ramp-load-0 = ▁
ramp-load-1 = ▂
ramp-load-2 = ▃
ramp-load-3 = ▄
ramp-load-4 = ▅
ramp-load-5 = ▆
ramp-load-6 = ▇
ramp-load-7 = █
ramp-load-foreground = ${colors.foreground-alt}

[module/memory]
type = internal/memory
interval = 2
format = <ramp-used>
format-prefix = "MEM "
format-prefix-foreground = ${colors.foreground-alt}
;format-underline = #4bffdc
label = %percentage_used%%

ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █
ramp-used-foreground = ${colors.foreground-alt}

[module/wlan]
type = internal/network
interface = wlp2s0
interval = 3.0

format-connected = <label-connected> <ramp-signal>
;format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 😱
ramp-signal-1 = 😠
ramp-signal-2 = 😒
ramp-signal-3 = 😊
ramp-signal-4 = 😃
ramp-signal-5 = 😈

ramp-signal-foreground = ${colors.foreground}
ramp-signal-font = 4

[module/workwlan]
inherit = module/wlan
interface = wlp3s0


[module/eth]
type = internal/network
interface = enp1s0f1
interval = 3.0

format-connected-underline = #55aa55
;format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/worketh]
inherit = module/eth
interface = enp12s0

[module/date]
type = internal/date
interval = 5

date = "%a, %d-%m-%Y"
date-alt = " %a, %d-%m-%Y"

time = %I:%M %p
#time-alt = %H:%M:%S
time-alt = %I:%M %p

;format-prefix = 
format-foreground = #b58900
;format-underline = #0a6cf5

label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume>
label-volume = %percentage%%
label-volume-foreground = ${root.foreground}

label-muted = 🔇
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #dc322f
;bar-volume-foreground-1 = #55aa55
;bar-volume-foreground-2 = #55aa55
;bar-volume-foreground-3 = #55aa55
;bar-volume-foreground-4 = #55aa55
;bar-volume-foreground-5 = #f5a70a
;bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

ramp-volume-0 = 🔈
ramp-volume-1 = 🔉
ramp-volume-2 = 🔊

[module/alsa]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <label>
format-prefix = "🌡"
format-prefix-foreground = ${colors.foreground-alt}
;format-underline = #f50a4d
format-warn = <label-warn>
;format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 0
margin-bottom = 0

; vim:ft=dosini

**Comment by drmarwat** [comment]
I finally managed to have a working polybar on my ratpoison with your settings + added jgmenu to it as well

**Comment by benofbrown** [comment]
Glad you got it sorted in the end, I'll close this off now.
