### ISSUE TITLE
polybar with i3

### ISSUE THREAD

**Issue by drmarwat** [benofbrown/dotfiles#3]
When I use your ploybar on i3 everything works perfectly but I cant see any workstations to move open windows to. What changes do I need to make to be able to see active and non active i3 windows?

**Comment by benofbrown** [comment]
As I said in a previous issue I've never even used i3. I've no idea. Maybe try contacting the polybar maintainers, they have this help page in their wiki: https://github.com/polybar/polybar/blob/master/SUPPORT.md
